#pragma once

#define IBOS_PORT_BYTES_ALIGNMENT (1UL << 0UL)
#define IBOS_PORT_STRUCT_ALIGNMENT (1UL << 2UL)
#define IBOS_PORT_MAX_ALIGNMENT (1UL << 16UL)

#define IBOS_PORT_WORD_SIZE_SHIFT 2UL
#define IBOS_PORT_WORD_SIZE (1UL << IBOS_PORT_WORD_SIZE)
